### ISSUE TITLE
type and responseCode should be included in Error.message

### ISSUE THREAD

**Issue by mateodelnorte** [nodemailer/smtp-connection#18]
Most applications will catch errors at a global level with process.on('uncaughtException' or a domain. And most app developers aren't going to peer through all their code dependencies to make sure unusual properties on errors are being logged by their global handlers. To make sure people don't miss type, responseCode, or any other critical error data, they should be included in the error message: 

https://github.com/andris9/smtp-connection/blob/7ccd9e4fbab836a1710f6e37beef0371ea83e9a6/src/smtp-connection.js#L384-L401

**Comment by BradRuderman** [comment]
How are SMTP TEMPFAILs handled with the smtp-connection library

**Comment by andris9** [comment]
Catching uncaughtException errors is a bad practice
