### ISSUE TITLE
smtp-connection doesn't play nice with smtp-server

### ISSUE THREAD

**Issue by KenGant** [nodemailer/smtp-connection#22]
While familiarizing myself with smtp-connection and -server, I set up one test program to email to itself. smtp-connection always produced an error when sending the message, because it was expecting a 2xx response during streaming, and smtp-server issues a '354 End data with <CR><LF>.<CR><LF>' response in the middle of the data.  SMTPConnection.prototype._actionDATA has a comment about and code to handle this exact situation, but SMTPConnection.prototype._actionStream needs the same handling.  I added the code to the _actionStream definition, and now smtp-connection will successfully talk with smtp-server.

**Comment by andris9** [comment]
Are you sure you are doing things in the right order? 354 is sent before the stream is even initiated and 200 is expected as the response for the stream end

**Comment by KenGant** [comment]
Well ... I'm pretty sure I'm doing things in the right order.  I've 
cobbled together the SMTP client and server sections by following the 
examples in the respective READMEs, and since I'm new to incorporating 
SMTP into my own code, I suppose it's possible that I've missed 
something.  However, I'm making liberal use of console.log, so every 
callback and listener has its own diagnostic message printed to the 
screen.  Have you tried this type of hookup yourself?  I would guess so, 
but it's worth asking. Do you want console logs, or the test program?

**Comment by andris9** [comment]
A failing test program that could be run and verified would be the best option

**Comment by donut87** [comment]
I have similar issues. 
I also have the problem that greetings starting with 250 are classified as error.

**Comment by andris9** [comment]
Reopen if you still have this problem
