### ISSUE TITLE
promise API

### ISSUE THREAD

**Issue by stevenvachon** [nodemailer/smtp-connection#36]
would be nice

**Comment by andris9** [comment]
This is probably not going to happen any time soon.

**Comment by stevenvachon** [comment]
Because?

**Comment by andris9** [comment]
Personally I don't like Promises too much. No reasoning, I don't say that Promises are bad, I just don't like them and I'm totally fine with callbacks. I had to include partial Promise support in Nodemailer because there were so many people asking for it but this was an exception.

**Comment by stevenvachon** [comment]
Ok, fair enough. Thanks.

**Comment by xpepermint** [comment]
+1

**Comment by dex4er** [comment]
@stevenvachon @xpepermint 

My proposition of such wrapper is: https://github.com/dex4er/js-smtp-connect-as-promised

I use it for some time. I didn't plan to publish it yet, but I could do it and even convert it to plain Javascript if someone thinks it might be useful.

**Comment by xpepermint** [comment]
@dex4er this looks promising, thx. Since I started using `async/await` I simple can not write code using callbacks anymore.
@andris9 are you still committed not to add promise support - it would be the winning solution?
