### ISSUE TITLE
don't work with smtp-server and smtp-connection

### ISSUE THREAD

**Issue by linejine** [nodemailer/smtp-connection#40]
I made a test program with smtp-server and smtp-connection
<smtp-server>
var SMTPServer = require('smtp-server').SMTPServer;
var SERVER_PORT = 2525;
var SERVER_HOST = '127.0.0.1';

var options = {
    authMethods: ['PLAIN', 'LOGIN', 'XOAUTH2'],
    disabledCommand: ['STARTTLS'], /*onAuth에서 text로 인증 할 경우 'STARTTLS' 설정*/
    banner: 'greeting server',
    onAuth: function(auth, session, callback) {
        if(auth.username !== 'testuser' || auth.password !== 'testpass') {
            return callback(new Error('Invalid username or password'));
        }
        callback(null, {user: 'testuser'}); //where 123 is the user id or similar property
    },
    onConnect: function(session, callback) {
        console.log("onConnect : " + session.remoteAddress);
        console.log("session : " + session.clientHostname);
        console.log('session.hostNameAppearsAs : ' + session.hostNameAppearsAs);
        return callback(); //Accept the connection
    },
    onMailFrom: function(address, session, callback) {
        console.log('onMailFrom : ' + address.address);
        return callback(); //Accept the address
    },
    onRcptTo: function(address, session, callback) {
        console.log('onRcptTo : ' + address.address);
        return callback();//Accept the address
    },
    onData: function(stream, session, callback) {
        stream.pipe(process.stdout); //print message to console
        stream.on('end', function() {
            callback(null, 'message end');
        });
    }
};

var server = new SMTPServer(options);

server.on('error', function(err) {
    console.log('server error : ' + err);
})
server.listen(SERVER_PORT, SERVER_HOST);

<smtp-connection>
var SMTPConnection = require('smtp-connection');

var options = {
    port: 2525,
    host: '127.0.0.1',
    authMethod: 'LOGIN'
};
var connection = new SMTPConnection(options);

connection.connect(function() {
    connection.wrtie('EHLO example.com\r\n');
    console.log('connection.connect');
});

var auth = {
    user: 'testuser',
    pass: 'testpass'
};

var envelope = {
    from: 'test@exmaple.com',
    to: 'kjj@exmaple.com'
};

connection.login(auth, function(err) {
    if(err) {
        console.log('connection.login error : ' + err);
        throw  err;
    }
    console.log('connection.login');
    connection.send(envelope, 'test', function(err, response) {
        if(err) {
            console.log('connection.send error : ' + err);
        } else {
            console.log('Message sent : ' + response.message);
        }
        //connection.quit();
        connection.close();
    });

});

I ran the smtp-sever and run the smtp-connection
but smtp-connection emited error.
events.js:141
      throw er; // Unhandled 'error' event
Error: Invalid greeting from server:
421 user-PC You talk too soon: 421 user-PC You talk too soon
    at SMTPConnection._actionGreeting (C:\Users\kjin\AppData\Roaming\npm\node_modules\smtp-connection\lib\smtp-connection.js:718:23)
    at SMTPConnection._processResponse (C:\Users\kjin\AppData\Roaming\npm\node_modules\smtp-connection\lib\smtp-connection.js:604:16)
    at SMTPConnection._onData (C:\Users\kjin\AppData\Roaming\npm\node_modules\smtp-connection\lib\smtp-connection.js:431:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Process finished with exit code 1

how can i do?

**Comment by andris9** [comment]
You are calling `login()` before `connect()` is finished. It should go like this:

```javascript
connection.connect(function() {
    connection.login(auth, function(err) {
        ...
    });
});
```
