### ISSUE TITLE
how can i do self signed certificate  / how can i do work with public ip address

### ISSUE THREAD

**Issue by linejine** [nodemailer/smtp-connection#41]
i solved #40  with your help.
but, i encountered another error.
Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:585:8)
[2016-02-22 10:12:07] ERROR: [fdFmGmQxdRY] self signed certificate

Process finished with exit code 1

i made smtp-server with authMethods 'PLAIN' and smtp-connection with authMethods 'PLAIN'
i don't know why it happened.
what can i do?
and i opened public ip address and domain name(ex. exam.example.com).
i made a smtp-server with my public ip address.
i ran the smtp-server, and sent email  from gmail to my domain name(ex. test@exam.example.com)
but, my smtp-server doesn't work.
what should i do?

**Comment by andris9** [comment]
when connecting use `tls` option:

```
var connection = new SMTPConnection({
    ...,
    tls: {
        rejectUnauthorized: false
    }
});
```
