### ISSUE TITLE
how can i do with public address

### ISSUE THREAD

**Issue by linejine** [nodemailer/smtp-connection#42]
i opened public ip address and domain name(ex. exam.example.com).
 i made a smtp-server with my public ip address.
 i ran the smtp-server, and sent email to my domain name(ex. test@exam.example.com) with google gmail web application.  but, my smtp-server doesn't response anything else.
 what should i do?

**Comment by andris9** [comment]
Github issues are meant to file bugs. This is not a bug but a support request. A better place to search for help would be StackOverflow or any other such channel.
