### ISSUE TITLE
Haraka

### ISSUE THREAD

**Issue by BradRuderman** [nodemailer/smtp-connection#44]
Has anyone used Haraka, specifically tried to create a plugin to send mail via an smtp relay. The smtp client provided in haraka is buggy, so looking how to send the available readstream into smtp-connection. More specifically go from the transaction object to the smtp-connection stream.

https://github.com/haraka/Haraka/blob/master/docs/Transaction.md

Thanks!

**Comment by andris9** [comment]
I guess it would be possible to use smtp-connection in Haraka but this is out of scope for smtp-connection development
